### ISSUE TITLE
Need Help!

### ISSUE THREAD

**Issue by igavelyuk** [igavelyuk/vue-shop#1]
Pls see project 

- [ ] https://burgerpandabc.com.ua/

and

- [ ] https://burgerpanda.com.ua/

and

- [ ] https://sushipandabc.com.ua/

Write something about project what you can see and what you like to see in the file
`FEATURESXX.md`
Where XX Your Number
Files Must be in `Feature` folder (if it not exist just create)
and made pull request

- Inside file something like this, you can improve inside structure, feel free.

```
Three sections proj overview
Pros
Cons
```

**Comment by harshalkh** [comment]
i have created a PR #2 please review
