### ISSUE TITLE
You can populate any component or create new / sub component.

### ISSUE THREAD

**Issue by igavelyuk** [igavelyuk/vue-shop#7]
You can populate any component or create new / sub component or extend. Use your imagination.

- Button
- Text
- Images
- Css classes.

**Comment by pablostellet** [comment]
Hi!
Let's team up?
Sometimes I use vue in my job and also if you agree, I could even learn something creating some tests 😄

**Comment by pablostellet** [comment]
@igavelyuk will you use any CSS framework like bootstrap?

**Comment by igavelyuk** [comment]
Basically would like to create minimalistic one, but it no problem make branch with bootstrap.
I saw some special framework for VUE, it was a lot written on Chinees, most probably I will use it.

**Comment by igavelyuk** [comment]
I'm very glad for any kind of support and collaboration.
